/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_k_hookjava_hookLib */

#ifndef _Included_com_k_hookjava_hookLib
#define _Included_com_k_hookjava_hookLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_k_hookjava_hookLib
 * Method:    test
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_k_hookjava_hookLib_test
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
